config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  resources :posts do
    member do
      post :save
    end
  end
  resources :categories
  resources :comments, only: [:create, :new]
end

app/models/post.rb
class Post < ActiveRecord::Base
  enum post_type: [:link, :text]
  validates :title, length: { maximum: 160 }, presence: true
  validates :link, length: { maximum: 2000 }
  validates :link, presence: true, if: :link?
  validates :body, presence: true, if: :text?
  validates :category_id, presence: true

  belongs_to :category
  belongs_to :user
  default_scope { order(updated_at: :desc).includes(:category).includes(:user) }
  self.per_page = 20

  acts_as_commentable
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy, :save]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @posts = Post.includes(:comment_threads).page(params[:page])
  end

  def show
    @comment = Comment.build_from(@post, current_user.id, '') if user_signed_in?
  end

  def new
    @post = Post.new
    @post.post_type = params[:post_type] if params[:post_type].present?
  end

  def create
    @post = Post.new post_params
    @post.user_id = current_user.id
    if @post.save
      redirect_to posts_path, flash: { :'alert-success' => 'Thanks for submitting your post!' }
    else
      flash.now[:'alert-danger'] = @post.errors.full_messages
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update post_params
      redirect_to posts_path, flash: { :'alert-success' => 'Your post has been updated.' }
    else
      flash.now[:'alert-danger'] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    if @post.destroy
      redirect_to posts_path, flash: { :'alert-success' => 'Your post has been removed.' }
    else
      redirect_to posts_path, flash: { :'alert-danger' => 'We were unable to remove that post. Perhaps someone already removed it.' }
    end
  end

  def save
    Nevernote.create_from @post, current_user.nevernote_api_key
    redirect_to @post, flash: { :'alert-success' => 'Saved to Nevernote!' }
  rescue
    redirect_to @post, flash: { :'alert-danger' => 'We were unable to save that to Nevernote' }
  end

  private

  def find_post
    @post = Post.find params[:id]
  end

  def post_params
    params.require(:post).permit(:title, :link, :body, :post_type, :category_id)
  end
end

app/views/posts/_actions.html.erb
<ul class="actions">
  <li><%= link_to "#{post.comment_threads.length} #{'comment'.pluralize(post.comment_threads.length)}", post_path(post, anchor: 'comments') %></li>
  <li><%= link_to 'edit', edit_post_path(post) %></li>
  <li><%= link_to 'delete', post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %></li>
  <% if current_user.nevernote_api_key.present? %>
  <li>
    <%= link_to 'save', save_post_path(post), method: :post %>
  </li>
  <% end %>
</ul>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <fieldset>
    <%= f.label :title %>
    <%= f.object.errors[:title] if f.object.errors[:title].present? %>
    <%= f.text_field :title %>
  </fieldset>

  <fieldset>
    <%= f.label :category_id %>
    <%= f.collection_select :category_id, categories, :id, :name, prompt: 'Pick a category, fool.' %>
  </fieldset>

  <% if f.object.link? %>
    <fieldset>
      <%= f.label :link %>
      <%= f.text_field :link %>
    </fieldset>
  <% end %>

  <% if f.object.text? %>
    <fieldset>
      <%= f.label :body %>
      <%= f.text_area :body %>
    </fieldset>
  <% end %>

  <%= f.hidden_field :post_type %>
  <%= f.submit class: 'btn btn-default' %>
<% end %>

app/views/posts/_list.html.erb
<ul class="posts">
<% posts.each do |post| %>
  <li>
    <%= render 'posts/slug', post: post %>
    <%= render 'posts/actions', post: post %>
  </li>
<% end %>
</ul>

<%= will_paginate posts %>

app/views/posts/_slug.html.erb
<div class="title">
  <%= link_to post.title, post_link(post) %>
</div>
<div class="tagline" title="<%= post.created_at %>">
  submitted <%= time_ago_in_words post.created_at %> ago
  to <%= link_to post.category.name, category_path(post.category) %>
  <%= "by #{post.user.username}" if post.user.present? %>
</div>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<%= render 'list', posts: @posts %>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<article class="post">
  <%= render 'slug', post: @post %>

  <% if @post.text? -%>
    <section class="body"><%= @post.body %></section>
  <% end -%>

  <%= render 'actions', post: @post %>

  <% if user_signed_in? %>
    <%= render 'comments/form', comment: @comment %>
  <% end %>

  <%= nested_ol @post.comment_threads, id: 'comments' do |comment| %>
    <div class="tagline" title="<%= comment.created_at %>">
      <%= comment.user.username %>
      <%= time_ago_in_words comment.created_at %> ago
    </div>
    <section class="body">
      <%= comment.body %>
    </section>
    <ul class="actions">
      <li><%= link_to 'reply', new_comment_path(parent_id: comment.id, format: 'js'), remote: true, method: :get %></li>
    </ul>
    <div id="reply-form-<%= comment.id %>" style="display: none">
    </div>
 <% end -%>
</article>