config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  resources :posts do
    member do
      post :save
    end
  end
  resources :categories
  resources :comments, only: [:create, :new]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bluit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container wrap">
  <div class="row">
    <div class="col-xs-12">
      <nav id="categories">
        <div class="dropdown">
          <button id="dLabel" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Categories
           <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
            <% categories.each do |c| -%>
              <li role="presentation"><%= link_to c.name, category_path(c), role: 'menuitem', tabindex: '-1' %></li>
            <% end -%>
          </ul>
        </div>
        <span class="separator">|</span>
        <ul class="category-links">
          <% categories.each_with_index do |c, i| %>
            <li>
              <% if i > 0 %>
                <span class="separator">-</span>
              <% end %>
              <%= link_to c.name, category_path(c) %>
            </li>
          <% end %>
        </ul>
      </nav>
      <header>
        <%= link_to 'Bluit', root_path %>
        <div id="session_actions">
          <% if user_signed_in? %>
            <%= link_to current_user.username, edit_user_registration_path(current_user) %>
            <span class="separator">|</span>
            <%= link_to 'logout', destroy_user_session_path, method: :delete %>
          <% else %>
            want to join? <%= link_to 'login', new_user_session_path %>
            or <%= link_to 'register', new_user_registration_path %>
          <% end %>
        </div>
      </header>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-xs-8">
        <main>
          <%= flash_messages(flash) unless flash.empty? %>
          <!-- BEGIN main content -->
          <%= yield %>
          <!-- END main content -->
        </main>
      </div>
      <div class="col-xs-4">
        <nav id="sidebar">
          <%= link_to 'Submit a new link', new_post_path %>
          <%= link_to 'Submit a new text post', new_post_path(post_type: :text) %>
          <%= link_to 'Create a new category', new_category_path %>
          <div>
            <%= yield :sidebar %>
          </div>
        </nav>
      </div>
    </div>
  </div>
  <div class="push"></div>
</div>
<footer>
  Use of this site constitutes acceptance of the <a 47 href="http://dresdenfiles.wikia.com/wiki/Unseelie_Accords">Unseelie Accords</a>.
</footer>

</body>
</html>